version: "3"
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./www:/shared/httpd
      - ./nginx.conf:/etc/nginx/nginx.conf
    links:
      - php
  php:
    image: devilbox/php-fpm:5.6-work
    volumes:
      - ./www:/shared/httpd
    links:
      - db
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
    restart: always
    ports:
      - "3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    volumes:
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    ports:
      - "3005:80"
    links:
      - db
